# Generated by Django 4.0.1 on 2022-02-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/profile_img/default.jpg', null=True, upload_to='images/profile_img/'),
        ),
    ]
