# Generated by Django 4.0.5 on 2022-07-20 11:29

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_phone_profile_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='images/profile_img/default.jpg', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[250, 250], upload_to='images/profile_img/'),
        ),
    ]
