# Generated by Django 4.0.5 on 2022-07-24 05:44

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='images/profile_img/default.jpg', force_format='JPEG', keep_meta=True, null=True, quality=-1, scale=None, size=[250, 250], upload_to='images/profile_img/'),
        ),
    ]
