# Generated by Django 4.0.1 on 2022-02-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_tag_rename_date_article_created_reviews_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
