# Generated by Django 4.0.1 on 2022-02-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_alter_article_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='discription',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
