# Generated by Django 4.0.1 on 2022-04-21 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_article_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Comments',
        ),
    ]
