# Generated by Django 4.0.1 on 2022-04-21 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_rename_reviews_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
