# Generated by Django 4.0.1 on 2022-04-21 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_rename_comments_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='value',
        ),
    ]
