# Generated by Django 4.0.1 on 2022-06-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_remove_comment_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
