# Generated by Django 4.0.5 on 2022-07-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0023_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, default='images/blog_img/no-photo.jpg', null=True, upload_to='images/blog_img/'),
        ),
    ]
