# Generated by Django 4.0.5 on 2022-07-20 11:34

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0024_alter_article_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='images/blog_img/no-photo.jpg', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1200, 720], upload_to='images/blog_img/'),
        ),
    ]
