# Generated by Django 4.0.5 on 2022-07-22 03:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0025_alter_article_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text_field',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
