# Generated by Django 4.0.5 on 2022-07-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0026_alter_article_text_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text_field',
            field=models.TextField(blank=True, null=True),
        ),
    ]
