# Generated by Django 4.0.5 on 2022-07-22 04:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0027_alter_article_text_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text_field',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
