# Generated by Django 4.0.5 on 2022-07-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0028_alter_article_text_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='discription',
            field=models.CharField(max_length=300),
        ),
    ]
