# Generated by Django 4.0.5 on 2022-07-23 07:21

import ckeditor_uploader.fields
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0029_alter_article_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='images/blog_img/no-photo.jpg', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1200, 720], upload_to='images/blog_img/', verbose_name='Thumbnail Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_field',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content'),
        ),
    ]
