# Generated by Django 4.0.5 on 2022-07-24 05:44

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0030_alter_article_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='images/blog_img/no-photo.jpg', force_format='JPEG', keep_meta=True, null=True, quality=-1, scale=None, size=[1200, 720], upload_to='images/blog_img/', verbose_name='Thumbnail Image'),
        ),
    ]
