# Generated by Django 4.0.5 on 2022-08-31 04:30

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0031_alter_article_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='heading', unique=True),
        ),
    ]
