# Generated by Django 4.0.5 on 2022-08-31 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0032_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
